name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build package
        run: npm run build

  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            example/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Check build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "❌ dist/index.js not found"
            exit 1
          fi
          if [ ! -f "dist/index.esm.js" ]; then
            echo "❌ dist/index.esm.js not found"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "❌ dist/index.d.ts not found"
            exit 1
          fi
          echo "✅ All build outputs are present"

      - name: Install example dependencies
        working-directory: ./example
        run: npm ci

      - name: Build example
        working-directory: ./example
        run: npm run build

      - name: Verify example build output
        working-directory: ./example
        run: |
          if [ ! -f "build/index.html" ]; then
            echo "❌ Example build/index.html not found"
            exit 1
          fi
          if [ ! -d "build/static" ]; then
            echo "❌ Example build/static directory not found"
            exit 1
          fi
          echo "✅ Example build completed successfully"
